---
# tasks file for esxi_ubuntu_deploy
- name: Deploy VM
  community.vmware.vmware_guest:
    hostname: '{{ hostname_name }}'
    username: '{{ username }}'
    password: '{{ password }}'
    validate_certs: no
    datacenter: '{{ datacenter_name }}'
    name: '{{ vm_name }}'
    state: poweredon
    guest_id: '{{ vm_guest_id }}'
    folder: '{{ folder }}'
    datastore: '{{ datastore_name }}'
    hardware:
      memory_mb: '2048'
      num_cpus: '1'
    disk:
      - size_gb: '25'
        type: thin
        datastore: '{{ datastore_name }}'
    cdrom:
      - type: iso
        iso_path: '[{{ datastore_name }}] {{ iso_file_path }}'
    networks:
      - name: '{{ network_name }}'
        device_type: vmxnet3