# tasks/main.yml
- name: Deploy Ubuntu VM on ESXi
  community.vmware.vmware_guest:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi_username }}"
    password: "{{ esxi_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    datastore: "{{ datastore }}"
    folder: "/vm"
    guest_id: "{{ vm_guest_id }}"
    hardware:
      memory_mb: 1024
      num_cpus: 2
    disk:
      - size_gb: 10
        type: thin
        datastore: "{{ datastore }}"
    cdrom:
      type: iso
      iso_path: "{{ iso_path }}"
    networks:
      - name: "{{ network_name }}"
        device_type: vmxnet3
    state: poweredon
  delegate_to: localhost
